alias ls="ls --color"
alias ll="ls --color -alh"
alias zshconf="vim ~/.zshrc"
alias vimconf="vim ~/.vimrc"
alias bashconf="vim ~/.bash_profile"
alias gs="git status"
alias gcm="git commit -m"
alias tmuxconf="vim ~/.tmux.conf"
